accountapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from accountapp.views import AccountCreateView,AccountDetailView,AccountUpdateView,AccountDeleteView
from accountapp import views

app_name = 'accountapp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name = 'projectapp'

urlpatterns = [
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('list/', ProjectListView.as_view(), name='list')
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body>

{% include 'header.html' %}

<button type="button" class="btn btn-primary">Primary</button>
{% block content %}
{% endblock %}

{% include 'footer.html' %}

</body>
</html>

templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <meta name="viewport" content="width=device-width, initioal-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
            integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'base.css' %}?v=0.1">


</head>

templates/header.html
<div class="main_header">
    <div class="testiii">
        <h1>pragmatic</h1>
    </div>
    <div style="text-align:center;">
        <a href="{% url 'projectapp:list' %}">
            <span>Project</span>
        </a>

        <a href="{% url 'subscribeapp:list' %}">
            <span>ScList</span>
        </a>

        <a href="{% url 'articleapp:list' %}">
            <span>List</span>
        </a>

        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
            <span>Login</span>
        </a>
        <a href="{% url 'accountapp:create' %}">
            <span>SignUp</span>
        </a>
        {% else %}

        <a href="{% url 'accountapp:detail' pk=user.pk %}">
            <span>MyPage</span>
        </a>

        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
            <span>Logout</span>
        </a>
        {% endif %}

    </div>
</div>
<hr>